server:
    port: 9201
    allows-origins: http://localhost:4200

jwt:
  publicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvWVuSCvPmtNOK22ODjiI
    yi2QA2AN54jOL5HXVSrMBTnwgX2L0iWnvRDTMgcDYvItTdvDkqFIPweCxvfMpJaP
    Im2glgDkSfBhlVj9mVj2P9aX9W1uNmMiLy0II4MGmybFz5YAtwGeR0Mfxm858NxE
    vwaihUW0H2h0QKauq5EXJtVCNg7ux8h7d2d14ICiIKvXiMH4JmOTnxSHRJ/ygz7e
    J2On2KwkQCG0IVrosDoOrTLJpP28BaUG/iN/BXXNn+7+RCjGw1s7ovRnqX16tYIJ
    ZpnjFi71/wp37QeCe6C2pWB/OEPlnhvJ7q9k+8KTyRbZ+BKTr3xBGfUAInh5vqip
    9QIDAQAB
    -----END PUBLIC KEY-----

logging:
  level:
    comcast.sigma: INFO
    org.hsqldb: DEBUG

hibernate:
    jdbc:
        time_zone: UTC
 
#Enable to show parameter and result values
#logging.level.org.hibernate.type.descriptor.sql: trace

monitoring:
    datasource:
        jdbc-url: jdbc:sqlserver://ctilxdb-dt-1d.cable.comcast.com:4951;DatabaseName=Monitoring
        username: monitoring
        password: 6kQydKjw6YzUjt2q4rWSrxYZ
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        maximum-pool-size: 5
        hikari:
            idle-timeout: 10000

spring:
    jpa:
        #Set to true to show generated queries
        show-sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: 'validate'
        #Enable to show query statistics
        #properties.hibernate.generate_statistics: trace
    #Write dates as timestamps
    jackson.serialization.write-dates-as-timestamps: true
